# brownie default values made explicit
compiler:
    evm_version: null
    solc:
        version: null
        optimizer:
            enabled: true
            runs: 200
        # https://eth-brownie.readthedocs.io/en/stable/compile.html#compiler-settings
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
    vyper:
        version: null

# exclude Ownable when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
# reports:
#   exclude_contracts:
#     - Ownable
